name: colorless-site
version: '0.0.0'
category: Web
synopsis: Colorless Site
description: Colorless Site
maintainer: Joe Vargas
extra-source-files:
- package.yaml
- README.md
ghc-options: -Wall
default-extensions:
- ConstraintKinds
- DeriveGeneric
- DuplicateRecordFields
- FlexibleContexts
- FlexibleInstances
- GADTs
- GeneralizedNewtypeDeriving
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- NamedFieldPuns
- OverloadedStrings
- RankNTypes
- ScopedTypeVariables
- TupleSections
- TypeApplications
- TypeOperators
library:
  dependencies:
  - aeson
  - base
  - bytestring
  - containers
  - data-default
  - envparse
  - errors
  - exceptions
  - http-api-data
  - http-client
  - http-client-tls
  - monad-control
  - monad-logger
  - mtl
  - path-pieces
  - scientific
  - servant
  - servant-blaze
  - servant-client
  - servant-server
  - stm
  - text
  - text-conversions
  - time
  - transformers
  - transformers-base
  - unordered-containers
  - wai
  - warp
  source-dirs: library
executables:
  colorless-site:
    dependencies:
    - base
    - colorless-site
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: executable
tests:
  colorless-site-suite:
    dependencies:
    - aeson
    - base
    - colorless-site
    - containers
    - hspec
    - text
    - vector
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Spec.hs
    source-dirs: tests
